# Minimal Home Assistant config for Vistapool development (Core in devcontainer)

homeassistant:
  name: Vistapool Dev
  time_zone: Europe/Prague
  country: CZ
  language: en

# Enable a sane default set of core integrations (UI, config, etc.).
default_config:

# Logging: verbose for your custom integration, quieter for noisy deps.
logger:
  default: info
  logs:
    custom_components.vistapool: debug
    pymodbus: warning
    homeassistant.components.http: warning

# Lightweight database settings for development (keeps DB small).
recorder:
  db_url: sqlite:////config/home-assistant_v2.db
  commit_interval: 30
  auto_purge: true
  purge_keep_days: 3

# Keep recent history/logbook for debugging, without heavy retention.
history:
logbook:
frontend:
api:

# Example Modbus TCP hub for Vistapool (adjust host/port as needed).
# modbus:
#   - name: vistapool_hub
#     type: tcp
#     host: 127.0.0.1
#     port: 8899
#     timeout: 5
#     delays:
#       between_messages: 10

panel_custom:
  - name: panel_integrations
    sidebar_title: Integrations
    sidebar_icon: mdi:connection
    url_path: "config/integrations"
    module_url: /api/hassio/app/entrypoint.js
    embed_iframe: true
    require_admin: true
  - name: panel_automations
    sidebar_title: Automations
    sidebar_icon: mdi:robot
    url_path: "config/automation"
    module_url: /api/hassio/app/entrypoint.js
    embed_iframe: true
    require_admin: true
