name: Hassfest

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - "custom_components/vistapool/**"
  pull_request:
    paths:
      - "custom_components/vistapool/**"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"
