name: Validate with Hassfest

permissions:
  contents: read
  
on:
  workflow_dispatch:
  push:
    paths:
      - 'custom_components/vistapool/**'
  pull_request:
    paths:
      - 'custom_components/vistapool/**'
  # schedule:
  #   - cron:  '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"
