name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'release-please--*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      - name: Extract version from CHANGELOG.md
        if: startsWith(github.ref, 'refs/heads/release-please--')
        run: |
          VERSION=$(grep -m1 -oP '^## \[\K[^\]]+' CHANGELOG.md)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update manifest.json version
        if: startsWith(github.ref, 'refs/heads/release-please--')
        run: |
          jq ".version=\"$VERSION\"" custom_components/vistapool/manifest.json > tmp.$$.json && mv tmp.$$.json custom_components/vistapool/manifest.json

      - name: Commit manifest.json version bump
        if: startsWith(github.ref, 'refs/heads/release-please--')
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add custom_components/vistapool/manifest.json
          git commit -m "chore(manifest): bump version to $VERSION"
          git push