name: Unit Tests

on:
  workflow_dispatch:
  push:
    paths:
      - "custom_components/vistapool/**"
      - "tests/**"
  pull_request:
    paths:
      - "custom_components/vistapool/**"
      - "tests/**"

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install homeassistant

      - name: Run tests with coverage
        run: |
          pytest --cov=custom_components/vistapool --cov-report=xml --junitxml=junit.xml -o junit_family=legacy --disable-warnings -v

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          use_oidc: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          use_oidc: true
