name: Type Check

on:
  push:
    branches:
      - "main"
    paths:
      - "custom_components/neopool/**"
      - ".github/workflows/typecheck.yaml"
      - "pyrightconfig.json"
  pull_request:
    paths:
      - "custom_components/neopool/**"
      - ".github/workflows/typecheck.yaml"
      - "pyrightconfig.json"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  basedpyright:
    name: BasedPyright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install basedpyright homeassistant-stubs 'neopool-modbus>=4.5.3'

      - name: Run BasedPyright
        run: basedpyright custom_components/neopool
